In [1]:
import numpy as np


In [2]:
ndim = 2
matrix = np.eye(2*ndim, 2*ndim)
matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
dt = 1
for i in range(ndim):
    matrix[i, ndim+ i] = dt

matrix


array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
mean_pos = np.array(
    [[1],
     [2],
     [6],
     [10]]
)
mean_vel = np.zeros_like(mean_pos)
mean = np.r_[mean_pos, mean_vel]
mean


array([[ 1],
       [ 2],
       [ 6],
       [10],
       [ 0],
       [ 0],
       [ 0],
       [ 0]])

In [11]:
measurement = mean_pos


In [14]:
2 * _std_weight_position * measurement[3]

array([1.])

In [19]:
_std_weight_position = 1./20
_std_weight_velocity = 1./160

std = [
        2 * _std_weight_position * measurement[3][0],
        2 * _std_weight_position * measurement[3][0],
        1e-2,
        2 * _std_weight_position * measurement[3][0],
        10 * _std_weight_velocity * measurement[3][0],
        10 * _std_weight_velocity * measurement[3][0],
        1e-5,
        10 * _std_weight_velocity * measurement[3][0]]
covariance = np.diag(np.square(std))
covariance

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 1.00000e-04, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 3.90625e-01,
        0.00000e+00, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        3.90625e-01, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 1.00000e-10, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 3.90625e-01]])